[package]
name = "tmsn"
version = "0.1.2"
authors = ["Julaiti Alafate <jalafate@gmail.com>"]

[dependencies]
bufstream = "0.1.3"
env_logger = "0.5.5"
log = "0.4.1"
serde = "1.0.33"
serde_derive = "1.0.33"
serde_json = "1.0.11"
time = "0.1.39"
